CREATE DATABASE bdpratica03;
USE bdpratica03;


CREATE TABLE DEPARTAMENTO (
    COD_DEPART INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    DATA_INICIAL DATE
);

CREATE TABLE FUNCIONARIO (
    COD_FUN INT PRIMARY KEY AUTO_INCREMENT,
    FUN_NOM VARCHAR(100) NOT NULL,
    FUN_CPF VARCHAR(11) NOT NULL UNIQUE,
    FUN_SAL DECIMAL(6,2) CHECK (FUN_SAL >= 1000.00),
    FUN_SEX CHAR(1) CHECK (FUN_SEX IN ('M', 'F')),
    COD_FUN_SUP INT,
    FOREIGN KEY (COD_FUN_SUP) REFERENCES FUNCIONARIO(COD_FUN),
    COD_FUN_DEPART INT,
    FOREIGN KEY (COD_FUN_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
);


CREATE TABLE LOCALIZACAO (
    COD_DEPART INT, 
    LOCAL VARCHAR(252),
    PRIMARY KEY (COD_DEPART, LOCAL),  
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
);

CREATE TABLE DEPENDENTE (
    COD_FUNC INT,
    SEQ INT,
    NOME VARCHAR(100) NOT NULL,
    PARENTESCO VARCHAR(30) NOT NULL CHECK (PARENTESCO IN ('PAI', 'MÃE', 'IRMAOS', 'FILHO')),
    DATA_NASC DATE,
    PRIMARY KEY (COD_FUNC, SEQ),
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUN)
);

CREATE TABLE PROJETO (
    COD_PROJ INT PRIMARY KEY AUTO_INCREMENT,
    COD_DEPART INT,
    TITULO VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(252),
    DATA_CAD DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
);

CREATE TABLE PARTICIPA (
    COD_FUNC INT,
    COD_PROJ INT,
    HORAS VARCHAR(50),
    PRIMARY KEY (COD_FUNC, COD_PROJ),
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUN),
    FOREIGN KEY (COD_PROJ) REFERENCES PROJETO(COD_PROJ)
);



